### PR TITLE
:boom: Add strong types for `JSON.parse` and `JSON.stringify`

### PR DESCRIPTION
**Pull request by aaditmshah**

### CODE REVIEW

**Comment by aaditmshah** [comment]
Here is some documentation that explains the changes I made in detail.

- https://github.com/total-typescript/ts-reset/pull/123
- https://github.com/total-typescript/ts-reset/pull/124

Let me know if you have any additional questions.

**Comment by uhyo** [comment]
It's not that serious 😅 (I still think mine better _resets_ type definitions than theirs though!)

I think I can take time for review on this weekend. Thanks for additional explanation!

**Review by uhyo — APPROVED** [review]
Got it! Thank you 🙌

**Comment by aaditmshah** [comment]
> I regret to tell that the repo you mentioned is the biggest rival which upsets the author of this repo.

I completely understand.

> There must be something missing that could further improve this repo such that there are more stargazers.

I believe adding more comprehensive documentation, creating video tutorials and screencasts, and advertising via word of mouth should increase the popularity of this library significantly.

> It's not that serious :sweat_smile: (I still think mine better _resets_ type definitions than theirs though!)

Oh, yes. 100%. Using `@typescript/xxx` packages is the right way to reset the type definitions. It actually replaces the incorrect types instead of simply adding alternative type definitions, which from my personal experience is problematic as you can still use the incorrect type definitions.

> I think I can take time for review on this weekend. Thanks for additional explanation!

Thank you for approving and merging my changes so quickly. Let me know if there's any other way I can help make this library better.

Also, pardon my forthrightness but when will the next version of this library with my changes be released?

**Comment by uhyo** [comment]
I have to upgrade to TypeScript 5.0 before release the next version. I'll take time tomorrow 🙂

**Pull request merged**
