### PR TITLE
:boom: Add strong type definition for `fetch().json()`

### LINKED ISSUE #24: [feature request] stricter fetch().json()
Having a stricter `JSON.parse()` is fantastic, and is most of the reason I tried this library. But most of my json parsing is done through `fetch().json()`, which [still returns](https://github.com/uhyo/better-typescript-lib/blob/5ccaad358d8495528186acd8dcf88f38283cf55b/generated/lib.webworker.generated.d.ts#LL850) `Promise<any>`. It'd be nice if it could also return `JSONData`.

### PR DESCRIPTION
**Pull request by aaditmshah**
Closes #24. You can review this PR on a per-commit basis. Here are the main changes that I made.

1. I used the `TypeScript/src/lib/libs.json` file to get the list of lib files.
2. I split the lib files into source files and target files.
3. This change was necessary to generate the `lib.dom.d.ts` file.
4. I ran the `build:lib` and `build:diff` commands to regenerate the assets.
5. I removed `@typescript/lib-header` from the list of dependencies in the `tests` directory.
6. I added a strong type definition and a corresponding test for `fetch().json()`.

### CODE REVIEW

**Comment by aaditmshah** [comment]
@uhyo I don't know why the check is failing. It's working for me locally.

**Comment by uhyo** [comment]
I even got a different error. Let me try upgrading Node.js version on CI first 😨

**Comment by aaditmshah** [comment]
> @aaditmshah Running `npm install` in the `tests` directory seems to produce a diff in `package-lock.json`. Could you try that?

Downgraded to node version 16 and generated a `package-lock.json` version 2 file. The continuous integration test is passing now.

We should probably add an `.nvmrc` file to the repository. What do you think?

**Comment by uhyo** [comment]
Oh actually using version 3 would be file. I guess there was just something wrong with original commit. I tested locally with latest npm and it seems to work. Also Node.js on CI has been upgraded to CI should be happy with v3 lockfiles.

**Comment by uhyo** [comment]
CI was falling again so I pushed the result of `npm install` for fix. Does this look fine? 😇

**Comment by aaditmshah** [comment]
> CI was falling again so I pushed the result of `npm install` for fix. Does this look fine? 😇

Looks good to me.

**Review by uhyo — APPROVED** [review]
Awesome, thank you :smiley:

**Comment by uhyo** [comment]
I think I can release tomorrow 🙂

**Pull request merged**
