### PR TITLE
Several Improvements

### PR DESCRIPTION
**Pull request by graphemecluster**
It may be split into a couple of small PRs if you prefer.

By the way, are there any reasons to remove the documentations in `lib.es2015.reflect.d.ts`?

### CODE REVIEW

**Comment by uhyo** [comment]
Thanks for your interest in contributing 🙂 

> By the way, are there any reasons to remove the documentations in `lib.es2015.reflect.d.ts`?

No, we don't intend to reduce documentations from the original typings. If there's any, it is unintentional mistake. 😨

**Comment by graphemecluster** [comment]
I just make it ready for review, but I still find it not perfect enough.

If this PR is separated to multiple PRs by myself, it will probably be too many, so please review and choose what you would like to separate.

And please help me think of a good PR title.

Also, I would like to confirm whether I should not commit the generated files.

**Comment by graphemecluster** [comment]
I separated yesterday's commit into several small commits for your convenience of reviewing.

And I found two things to be improved:
- Remove the top line with triple-slash directive `/// <reference no-default-lib="true"/>` in the diff docs.
- Build the library base on each method declaration, so that we don't need to copy the abundant methods that we don't want to change and prevent accidentally forgetting to declare some methods

**Comment by graphemecluster** [comment]
It seems that `npm test` in the workflow is still using the old type definitions such that the check had failed. 🈚️

**Comment by uhyo** [comment]
Thanks, currently you need to commit generated type defs (generated by `build:lib` script).
Sorry for lack of documents :cry:

**Comment by graphemecluster** [comment]
By the way, I wonder why you only include the `build:package` script in the workflow. 🤔

**Comment by graphemecluster** [comment]
I suddenly come out with an idea that we can add a `noOfCaptureGroups` type parameter to the `replace` and `replaceAll` methods since the user should know how many capture groups they have. It is impractical to have a parameter typed `string | number`. The other parameters at the end are seldom used either.
And we don’t need to wait until https://github.com/microsoft/TypeScript/issues/45972 being solved too.

**Comment by uhyo** [comment]
Sorry for late response, overall LGTM!

> By the way, I wonder why you only include the build:package script in the workflow. 🤔

Maybe because changing committed source code during the test isn't quite good.

> Build the library base on each method declaration, so that we don't need to copy the abundant methods that we don't want to change and prevent accidentally forgetting to declare some methods

Yes :cry: I want to implement this when I have time.

> I suddenly come out with an idea that we can add a noOfCaptureGroups type parameter

That's interesting, but one worrying point is that user could lie about this... but it'd be fine if the current implementation already allows lies.

**Comment by graphemecluster** [comment]
> Yes 😢 I want to implement this when I have time.

Looking forward to your implementation! 😆

**Pull request merged**
